export const UI_TEXT = {
    vi: {
        appName: "Scan & Chat AI",
        settings: "Cài đặt",
        settingsDescription: "Tùy chỉnh ngôn ngữ và giao diện",

        homeSubtitle: "Quét tài liệu · OCR · Hỏi đáp thông minh với AI",

        homeActionsAria: "Điều hướng chính",

        scanBtn: "Scan tài liệu",
        scanAria: "Quét tài liệu",

        historyBtn: "Lịch sử chat",
        historyAria: "Xem lịch sử chat",

        benefitFast: "Nhanh",
        benefitAccurate: "Chính xác",
        benefitPrivate: "Riêng tư",

        settingsTitle: "Cài đặt",
        backHome: "Quay về trang chủ",

        appearanceTitle: "Giao diện",
        themeLabel: "Chế độ sáng/tối",
        themeDesc: "Chọn giao diện phù hợp với điều kiện chiếu sáng của bạn",
        themeLight: "Sáng",
        themeDark: "Tối",

        languageTitle: "Ngôn ngữ",
        systemLangLabel: "Ngôn ngữ giao diện",
        systemLangDesc: "Thay đổi ngôn ngữ hiển thị của ứng dụng",

        targetLangLabel: "Ngôn ngữ dịch mặc định",
        targetLangDesc: "Ngôn ngữ sẽ được sử dụng khi dịch tài liệu quét",

        langVi: "Vietnamese (Tiếng Việt)",
        langEn: "English",
        scanLangAutoDetect: "Tự động phát hiện ngôn ngữ",

        dropdownSearchPlaceholder: "Tìm kiếm...",
        dropdownNoResults: "Không tìm thấy kết quả",

        authLoginTitle: "Đăng nhập",
        authLoginSubtitle: "Tiếp tục với tài khoản ScanGo của bạn",
        authRegisterTitle: "Tạo tài khoản",
        authRegisterSubtitle: "Bắt đầu trải nghiệm scan & chat AI",
        authEmail: "Email",
        authPassword: "Mật khẩu",
        authPasswordHint: "Tối thiểu 8 ký tự, gồm chữ và số",
        authName: "Tên hiển thị",
        authLoginBtn: "Đăng nhập",
        authRegisterBtn: "Đăng ký",
        authSubmitting: "Đang xử lý...",
        authNoAccount: "Chưa có tài khoản?",
        authHaveAccount: "Đã có tài khoản?",
        authAcceptTerms: "Tôi đồng ý với điều khoản sử dụng và chính sách bảo mật.",
        authMustAcceptTerms: "Bạn cần đồng ý điều khoản trước khi đăng ký.",
        authLoginGenericError: "Đăng nhập thất bại. Vui lòng thử lại.",
        authRegisterGenericError: "Đăng ký thất bại. Vui lòng thử lại.",
        authLogout: "Đăng xuất",
        authVerifyEmailHint: "Email của bạn chưa được xác minh. Kiểm tra hộp thư để kích hoạt tài khoản.",
        authInAppNotice:
          "Bạn đang mở trong ứng dụng khác nên đăng nhập Google có thể bị chặn. Hãy mở bằng trình duyệt (Chrome/Safari), hoặc dùng email + mật khẩu bên dưới.",
        authOpenInBrowser: "Mở trong trình duyệt",
        authInAppIosHint:
          "Bấm nút chia sẻ hoặc “•••” ở góc màn hình, rồi chọn “Mở trong Safari/Chrome”.",
        authCopyLink: "Sao chép liên kết",
        authLinkCopied: "Đã sao chép liên kết",
        inAppGateTitle: "Mở trong trình duyệt để tiếp tục",
        inAppGateBody:
          "Đăng nhập Google không hoạt động trong ứng dụng này. Hãy mở ScanGo bằng Chrome hoặc Safari để đăng nhập.",
        inAppGateDismiss: "Tiếp tục tại đây",

        infoTitle: "Thông tin",
        appDesc: "Ứng dụng trợ lý AI dành cho du khách",
        appSubDesc: "Quét tài liệu, dịch, và chat với AI",
        plansTitle: "Các gói dịch vụ",
        plansCurrentBadge: "Đang dùng",
        plansLimitFree: "3 lượt quét + 5 lượt hỏi mỗi tuần",
        plansLimitLite: "20 lượt quét + 50 lượt hỏi trong 1 tuần",
        plansLimitBasic: "20 lượt quét + 50 lượt hỏi mỗi tuần",
        plansLimitPro: "100 lượt quét + 200 lượt hỏi mỗi tuần",
        plansLimitUnlimited: "999 lượt quét + 999 lượt hỏi mỗi tuần",
        plansDuration30: "30 ngày",
        plansDuration7: "7 ngày",
        plansDuration365: "365 ngày",
        plansInternal: "Nội bộ",
        plansNote: "Bấm \"Mua\" rồi quét QR để nâng cấp. Hạn mức làm mới vào đầu mỗi tuần.",

        // ========== PAYMENT / CHECKOUT ==========
        buyBtn: "Mua",
        plansDowngradeHint: "Đổi khi gói hiện tại hết hạn",
        checkoutTitle: "Mua gói",
        checkoutScanQr: "Quét mã QR bằng app ngân hàng để chuyển khoản",
        checkoutBank: "Ngân hàng",
        checkoutAccountNo: "Số tài khoản",
        checkoutAccountHolder: "Chủ tài khoản",
        checkoutAmount: "Số tiền",
        checkoutContent: "Nội dung chuyển khoản",
        checkoutContentWarn: "Vui lòng GIỮ NGUYÊN nội dung này để hệ thống tự động xác nhận.",
        checkoutCopy: "Sao chép",
        checkoutCopied: "Đã sao chép",
        checkoutWaiting: "Đang chờ bạn chuyển khoản…",
        checkoutWaitingHint: "Sau khi chuyển xong, để yên màn hình này — gói sẽ tự kích hoạt trong ít phút.",
        checkoutPaidToast: "Thanh toán thành công! Gói đã được kích hoạt.",
        checkoutExpiresIn: "Hết hạn sau",
        checkoutExpired: "Đơn đã hết hạn.",
        checkoutRetry: "Tạo đơn mới",
        checkoutCreateError: "Không tạo được đơn. Vui lòng thử lại.",
        checkoutNotConfigured: "Thanh toán chưa được cấu hình. Vui lòng liên hệ quản trị viên.",

        // Payment status labels (sync với PaymentOrderStatuses .NET)
        payStatusPending: "Chờ thanh toán",
        payStatusPaid: "Đã thanh toán",
        payStatusExpired: "Hết hạn",
        payStatusCancelled: "Đã huỷ",
        payStatusRefunded: "Đã hoàn tiền",

        // ========== APP SHELL TITLES ==========
        homeTitle: "Trang chủ",
        conversationTitle: "Hội thoại",

        // ========== SCAN ==========
        scanTitle: "Scan tài liệu",
        scanStep1: "Bước 1: Chọn ảnh",
        scanStep2: "Bước 2: Chọn loại tài liệu",
        scanStep3: "Bước 3: Chọn ngôn ngữ",

        scanFileInputAria: "Chọn file hình ảnh",

        scanUploadSelect: "Chọn ảnh",
        scanUploadSelected: "✓ Đã chọn",
        scanUploadSelectAria: "Chọn ảnh",
        scanUploadSelectedAria: "Đổi ảnh đã chọn",

        scanPreviewAlt: "Xem trước ảnh",

        scanTopicDesc: "Chọn loại tài liệu để AI hiểu rõ nội dung hơn",

        topicLabels: {
            product: "Thông tin sản phẩm",
            history: "Thông tin lịch sử",
            place: "Địa điểm / Du lịch",
            general: "Tài liệu chung",
        },

        scanSourceLang: "Ngôn ngữ gốc (OCR)",
        scanTargetLang: "Dịch sang ngôn ngữ",

        scanGroupBest: "Hỗ trợ tốt nhất",
        scanGroupOther: "Các ngôn ngữ khác",

        scanSubmit: "Scan & Chat",
        scanProcessing: "Đang xử lý...",
        scanHelp: "Chọn ảnh tài liệu, hóa đơn, menu, hay bất kỳ tài liệu nào bạn muốn dịch hoặc hỏi",

        scanErrNotImage: "Vui lòng chọn file hình ảnh",
        scanErrTooLarge: "File quá lớn (tối đa 10MB)",
        scanErrSubmit: "Lỗi khi xử lý hình ảnh. Vui lòng thử lại.",
        scanQuotaError:
          "Bạn đã hết lượt quét tuần này. Quota sẽ reset vào đầu tuần sau.",

        // ===== HISTORY =====
        historyTitle: "Lịch sử chat",
        historyLoading: "Đang tải lịch sử...",
        historyLoadError: "Không thể tải lịch sử chat",

        historyEmptyTitle: "Chưa có cuộc trò chuyện",
        historyEmptyDesc: "Bắt đầu bằng cách scan một tài liệu",

        historyUntitled: "Cuộc trò chuyện mới",
        historyOpenConversation: "Mở cuộc trò chuyện",

        historyRename: "Đổi tên",
        historyDelete: "Xóa",

        historyRenameTitle: "Đổi tên cuộc trò chuyện",
        historyRenamePlaceholder: "Nhập tên cuộc trò chuyện...",

        historyDeleteTitle: "Xóa cuộc trò chuyện",
        historyDeleteConfirm: "Bạn có chắc chắn muốn xóa cuộc trò chuyện này không?",

        historyRenameError: "Không thể đổi tên cuộc trò chuyện",
        historyDeleteError: "Không thể xóa cuộc trò chuyện",

        historySearchPlaceholder: "Tìm theo tiêu đề...",
        historyFilterAllTopics: "Tất cả chủ đề",
        historyLoadMore: "Xem thêm",
        historyLoadingMore: "Đang tải...",
        historyNoResults: "Không tìm thấy cuộc trò chuyện nào",
        historyShowingCount: (shown: number, total: number) =>
          `Hiển thị ${shown} / ${total}`,
        historyPaginationPrev: "Trước",
        historyPaginationNext: "Sau",
        historyPageOf: (page: number, totalPages: number) =>
          `Trang ${page} / ${totalPages}`,
        historyPerPage: "Mỗi trang",
        historyShowingRange: (from: number, to: number, total: number) =>
          `Hiển thị ${from}-${to} trong tổng số ${total} kết quả`,
        historyViewGrid: "Xem dạng lưới",
        historyViewList: "Xem dạng danh sách",
        historyColName: "Tên",
        historyColTopic: "Chủ đề",
        historyColCreated: "Ngày tạo",
        historyColActions: "Thao tác",

        save: "Lưu",
        cancelBtn: "Hủy",
        closeBtn: "Đóng",
        delete: "Xóa",
        // ========== CONVERSATION ==========
        convDefaultTitle: "Cuộc trò chuyện mới",

        // ========== ADMIN ==========
        adminTitle: "Quản trị",
        adminOpenLink: "Mở trang quản trị",
        adminAiSection: "Cấu hình AI",
        adminModelLabel: "Model AI",
        adminModelDesc: "Model Gemini dùng để phân tích & trả lời",
        adminModelFlash: "chất lượng cao",
        adminModelLite: "rẻ & nhanh",
        adminAiMockLabel: "Mock AI",
        adminAiMockDesc: "Bật = trả lời giả lập (không gọi Gemini, không tốn quota)",
        adminOcrMockLabel: "Mock OCR",
        adminOcrMockDesc: "Bật = OCR giả lập (không gọi OCR.Space)",
        adminTtsLabel: "Đọc bằng giọng Google (TTS)",
        adminTtsDesc:
          "Bật = giọng Google tự nhiên; Tắt = giọng mặc định của trình duyệt",
        adminSaving: "Đang lưu...",
        adminSaved: "Đã lưu ✓",
        adminLoadError: "Không tải được cấu hình",
        adminSaveError: "Lưu thất bại",

        logoutConfirmTitle: "Đăng xuất?",
        logoutConfirmMessage: "Bạn có chắc muốn đăng xuất khỏi tài khoản này?",

        adminUsersTitle: "Quản lý người dùng",
        adminUsersLink: "Quản lý người dùng",
        adminQuotaSection: "Quota miễn phí (mỗi tuần)",
        adminFreeScans: "Số lần quét / tuần",
        adminFreeAsks: "Số câu hỏi / tuần",
        adminSearchUser: "Tìm theo email hoặc tên...",
        adminFilterRole: "Lọc theo vai trò",
        adminFilterPlan: "Lọc theo gói",
        adminSortBy: "Sắp xếp theo",
        adminAll: "Tất cả",
        adminSortCreated: "Ngày đăng ký",
        adminSortLastLogin: "Đăng nhập gần nhất",
        adminSortEmail: "Email",
        adminSortName: "Tên",
        adminSortPlan: "Gói",
        adminSortStatus: "Trạng thái",
        adminSortRole: "Vai trò",
        adminSortConvos: "Hội thoại",
        adminSortTokens: "Token",
        adminSortAsc: "Tăng dần",
        adminSortDesc: "Giảm dần",
        adminColUser: "Người dùng",
        adminColRole: "Vai trò",
        adminColPlan: "Gói",
        adminColVerified: "Verify",
        adminColConvos: "Convo",
        adminColTokens: "Token",
        adminColQuota: "Quota tuần (quét/hỏi)",
        adminColStatus: "Trạng thái",
        adminColActions: "Thao tác",
        adminPlanPaid: "Trả phí",
        adminActionReset: "Reset quota",
        adminActionSuspend: "Khoá",
        adminActionUnsuspend: "Mở khoá",
        adminActionDelete: "Xoá",
        adminDeleteConfirm: "Xoá vĩnh viễn người dùng này (và toàn bộ dữ liệu)? Không thể hoàn tác.",
        adminMetricUsers: "Người dùng",
        adminMetricConvos: "Cuộc trò chuyện",
        adminMetricCalls: "Lượt gọi AI",
        adminMetricCost: "Ước tính chi phí Gemini",
        adminUsersEmpty: "Không có người dùng",
        adminBackToConfig: "Cấu hình AI",
        adminSelfDisabled: "Không thể thao tác lên chính mình",

        // ========== ADMIN PAYMENTS ==========
        adminPaymentsTitle: "Thanh toán",
        adminPaymentsDesc: "Log giao dịch, duyệt & hoàn tiền",
        adminPayFilterStatus: "Lọc trạng thái",
        adminPayColOrder: "Mã đơn",
        adminPayColUser: "Người dùng",
        adminPayColPlan: "Gói",
        adminPayColAmount: "Số tiền",
        adminPayColStatus: "Trạng thái",
        adminPayColCreated: "Tạo lúc",
        adminPayColPaid: "Trả lúc",
        adminPayColNote: "Ghi chú",
        adminPayColActions: "Thao tác",
        adminPayActionApprove: "Duyệt",
        adminPayActionReject: "Từ chối",
        adminPayActionRefund: "Hoàn tiền",
        adminPayEmpty: "Chưa có giao dịch",
        adminPayApproveConfirm: "Xác nhận đã nhận được tiền và cấp gói cho người dùng này?",
        adminPayRejectConfirm: "Từ chối / huỷ đơn này?",
        adminPayRefundTitle: "Đánh dấu đã hoàn tiền",
        adminPayRefundNote: "Ghi chú (vd: bạn — đã chuyển khoản lại tay)",
        adminPayRefundHint: "Chỉ ghi nhận đã hoàn tiền — KHÔNG thu hồi gói của người dùng.",
        adminPayActionError: "Thao tác thất bại",

        // ========== ADMIN PLAN STATS + REVENUE ==========
        adminPlanStatsTitle: "Người dùng theo gói",
        adminRevenueTitle: "Doanh thu",
        adminRevenueDesc: "Thống kê thu nhập theo ngày",
        adminRevenueRange: "Khoảng thời gian",
        adminRevenue7d: "7 ngày",
        adminRevenue30d: "30 ngày",
        adminRevenue90d: "90 ngày",
        adminRevenueTotal: "Tổng doanh thu",
        adminRevenueOrders: "Đơn đã thanh toán",
        adminRevenueRefunded: "Đã hoàn tiền",
        adminRevenueChartTitle: "Doanh thu theo ngày",
        adminRevenuePeak: "Cao nhất",
        adminRevenueEmpty: "Chưa có doanh thu",
        adminRevenueNote: "Doanh thu = các đơn đã thanh toán (đã loại đơn hoàn tiền). Múi giờ VN.",

        profileTitle: "Tài khoản",
        profileLink: "Tài khoản",
        profileAccount: "Thông tin tài khoản",
        profileEmail: "Email",
        profileName: "Tên",
        profileEmailVerified: "Xác minh email",
        profileVerifiedYes: "Đã xác minh",
        profileVerifiedNo: "Chưa xác minh",
        profileRole: "Vai trò",
        profilePlan: "Gói",
        profileMemberSince: "Tham gia từ",
        profileQuota: "Hạn mức tuần này",
        profileQuotaScans: "Lượt quét",
        profileQuotaAsks: "Câu hỏi",
        profileQuotaReset: "Reset lúc",
        profileUnlimited: "Không giới hạn",
        profileEdit: "Chỉnh sửa",
        profileEditTitle: "Chỉnh sửa hồ sơ",
        profileSave: "Lưu",
        profileCancel: "Huỷ",
        profileNameSaved: "Đã cập nhật tên ✓",
        profileNameError: "Không thể cập nhật tên. Vui lòng thử lại.",
        profileChangeAvatar: "Đổi ảnh đại diện",
        profileRemoveAvatar: "Xoá ảnh",
        profileRemoveAvatarTitle: "Xoá ảnh đại diện?",
        profileRemoveAvatarConfirm:
          "Ảnh đại diện hiện tại sẽ bị xoá. Bạn có chắc không?",
        profileAvatarSaved: "Đã cập nhật ảnh đại diện ✓",
        profileAvatarRemoved: "Đã xoá ảnh đại diện ✓",
        profileAvatarError: "Không thể cập nhật ảnh. Vui lòng thử lại.",
        profileAvatarTooLarge: "Ảnh quá lớn (tối đa 5MB).",
        profileAvatarNotImage: "Vui lòng chọn file hình ảnh.",
        verifyResend: "Gửi email xác minh",
        verifySent: "Đã gửi ✓",
        verifyLoading: "Đang xác minh...",
        verifySuccess: "Xác minh email thành công!",
        verifyError: "Link không hợp lệ hoặc đã hết hạn.",
        back: "Quay lại",
        authOr: "hoặc",
        authGoogleSubtitle: "Tiếp tục bằng tài khoản Google của bạn",
        authTermsNote:
          "Bằng việc tiếp tục, bạn đồng ý với Điều khoản & Chính sách bảo mật.",

        convBackToHistoryAria: "Quay về lịch sử",
        convBackToHistoryTitle: "Quay về danh sách trò chuyện",

        convActionRename: "Đổi tên",
        convActionDelete: "Xóa",

        convEmptyText: "Bắt đầu đặt câu hỏi về tài liệu của bạn",

        convStreamError: "Scan stream failed",
        convSendError: "Lỗi khi gửi tin nhắn. Vui lòng thử lại.",
        convSendErrorBubble: "Đã xảy ra lỗi. Vui lòng thử lại.",

        convInputPlaceholder: "Nhập câu hỏi...",
        convInputAria: "Nhập tin nhắn",
        convExpandAria: "Mở rộng ô nhập",
        convComposeTitle: "Soạn câu hỏi",
        convCharCount: "{count}/{max} ký tự",
        convCharLimitReached: "Đã đạt giới hạn ký tự",

        convSendAria: "Gửi tin nhắn",
        convStopAria: "Dừng sinh câu trả lời",
        convSpeakAria: "Đọc to câu trả lời",
        convStopSpeakAria: "Dừng đọc",
        convSpeakUnsupported: "Trình duyệt không hỗ trợ đọc văn bản",

        convBtnSendText: "Gửi",
        convBtnStopText: "Dừng",

        convImageAlt: "Ảnh đã tải lên",
        convImagePreviewAlt: "Xem ảnh",

        convRenameTitle: "Đổi tên cuộc trò chuyện",
        convRenamePlaceholder: "Nhập tên cuộc trò chuyện...",
        convRenameError: "Không thể đổi tên cuộc trò chuyện",

        convDeleteTitle: "Xóa cuộc trò chuyện",
        convDeleteConfirm: "Bạn có chắc chắn muốn xóa toàn bộ cuộc trò chuyện này không?",
        convDeleteError: "Không thể xóa cuộc trò chuyện",

        benefitFastDescription: "Xử lý siêu nhanh, cho kết quả gần như tức thì",
        benefitAccurateDescription: "OCR độ chính xác cao với AI kiểm chứng",
        benefitPrivateDescription: "Dữ liệu của bạn luôn an toàn và riêng tư",
        statAccuracy: "Độ chính xác",
        statSpeed: "Tốc độ TB",
        statConversations: "Ngôn ngữ",

        historyBtnDescription: "Truy cập lịch sử trò chuyện của bạn",
        scanBtnDescription: "Scan tài liệu nhanh chóng với AI-powered OCR",

        historyConversations: "Lịch sử cuộc trò chuyện",
        scanUploadCamera: "Chụp ảnh",
        scanUploadGallery: "Tải ảnh",

        // ========== COMMON ==========
        commonRetry: "Thử lại",
        commonClose: "Đóng",

        // ========== VERIFY ==========
        verifyErrorTitle: "Xác minh không thành công",

        // ========== AUTH ==========
        authRegisterRedirect: "Đang chuyển đến trang đăng nhập...",

        // ========== HOME ==========
        homeGreetingMorning: "Chào buổi sáng,",
        homeGreetingAfternoon: "Chào buổi chiều,",
        homeGreetingEvening: "Chào buổi tối,",
        homeGreetingFallback: "Bạn",
        homeCtaTitle: "Sẵn sàng quét?",
        homeCtaDesc: "Chụp hoặc tải ảnh lên để trích xuất và hỏi đáp với AI ngay.",
        homeQuotaTitle: "Hạn mức tuần này",
        homeQuotaPeriod: "7 ngày",
        homeQuotaLabel: "Lượt quét còn lại",
        homeQuotaUsedSuffix: "đã dùng",
        homeQuotaUnknown: "Hạn mức sẽ hiển thị khi có dữ liệu sử dụng.",
        homeQuotaUnlimited: "Không giới hạn",
        homeQuotaScans: "Lượt quét",
        homeQuotaAsks: "Lượt hỏi",
        homeQuotaResetHint: "Hạn mức làm mới vào đầu tuần sau.",
        homeQuickActions: "Lối tắt",
        homeTipsTitle: "Mẹo dùng nhanh",
        homeTip1: "Chụp ảnh rõ nét, đủ sáng để AI đọc chính xác hơn.",
        homeTip2: "Mở lại lịch sử để tiếp tục hỏi đáp về ảnh đã quét.",
        homeTip3: "Đổi ngôn ngữ và giao diện sáng/tối trong Cài đặt.",

        // ========== CONVERSATION (extra) ==========
        convQuotaError: "Bạn đã dùng hết lượt quét/hỏi đáp. Hãy nâng cấp hoặc thử lại sau.",
        convEmptyTitle: "Bắt đầu trò chuyện",
        convRenameSuccess: "Đã đổi tên cuộc trò chuyện",
        convDeleteSuccess: "Đã xóa cuộc trò chuyện",

        // ========== HISTORY (extra) ==========
        historyDeleteSuccess: "Đã xoá hội thoại",
        historyRenameSuccess: "Đã đổi tên hội thoại",
        historyNoResultsDesc: "Thử đổi từ khoá tìm kiếm hoặc bộ lọc chủ đề.",
        historyClearFilters: "Xoá bộ lọc",
        historyViewToggleLabel: "Kiểu hiển thị",
        historyActionsFor: "Tác vụ cho",
        historyPaginationLabel: "Phân trang",
        historyPaginationFirst: "Trang đầu",
        historyPaginationLast: "Trang cuối",
    },

    en: {
        appName: "Scan & Chat AI",
        settings: "Settings",
        settingsDescription: "Customize language and appearance",

        homeSubtitle: "Scan documents · OCR · Smart AI chat",

        homeActionsAria: "Main navigation",

        scanBtn: "Scan document",
        scanAria: "Scan a document",

        historyBtn: "Chat history",
        historyAria: "View chat history",

        benefitFast: "Fast",
        benefitAccurate: "Accurate",
        benefitPrivate: "Private",

        settingsTitle: "Settings",
        backHome: "Back to home",

        appearanceTitle: "Appearance",
        themeLabel: "Light / Dark mode",
        themeDesc: "Choose the interface that fits your environment",
        themeLight: "Light",
        themeDark: "Dark",

        languageTitle: "Language",
        systemLangLabel: "System language",
        systemLangDesc: "Change the display language of the application",

        targetLangLabel: "Default translation language",
        targetLangDesc: "This language will be used to translate scanned documents",

        langVi: "Vietnamese (Tiếng Việt)",
        langEn: "English",
        scanLangAutoDetect: "Auto Detect",

        dropdownSearchPlaceholder: "Search...",
        dropdownNoResults: "No results found",

        authLoginTitle: "Sign in",
        authLoginSubtitle: "Continue with your ScanGo account",
        authRegisterTitle: "Create account",
        authRegisterSubtitle: "Start scanning & chatting with AI",
        authEmail: "Email",
        authPassword: "Password",
        authPasswordHint: "Min 8 characters, letters + numbers",
        authName: "Display name",
        authLoginBtn: "Sign in",
        authRegisterBtn: "Sign up",
        authSubmitting: "Working...",
        authNoAccount: "No account yet?",
        authHaveAccount: "Already have an account?",
        authAcceptTerms: "I agree to the Terms of Service and Privacy Policy.",
        authMustAcceptTerms: "You must accept the terms to register.",
        authLoginGenericError: "Sign in failed. Please try again.",
        authRegisterGenericError: "Sign up failed. Please try again.",
        authLogout: "Sign out",
        authVerifyEmailHint: "Your email isn't verified yet. Check your inbox to activate.",
        authInAppNotice:
          "You're inside another app, so Google sign-in may be blocked. Open this page in a browser (Chrome/Safari), or use email + password below.",
        authOpenInBrowser: "Open in browser",
        authInAppIosHint:
          "Tap the share or “•••” menu in the corner, then choose “Open in Safari/Chrome”.",
        authCopyLink: "Copy link",
        authLinkCopied: "Link copied",
        inAppGateTitle: "Open in a browser to continue",
        inAppGateBody:
          "Google sign-in doesn't work inside this app. Open ScanGo in Chrome or Safari to sign in.",
        inAppGateDismiss: "Continue here anyway",

        infoTitle: "Information",
        appDesc: "AI assistant application for travelers",
        appSubDesc: "Scan documents, translate, and chat with AI",
        plansTitle: "Plans",
        plansCurrentBadge: "Current",
        plansLimitFree: "3 scans + 5 questions per week",
        plansLimitLite: "20 scans + 50 questions for the week",
        plansLimitBasic: "20 scans + 50 questions per week",
        plansLimitPro: "100 scans + 200 questions per week",
        plansLimitUnlimited: "999 scans + 999 questions per week",
        plansDuration30: "30 days",
        plansDuration7: "7 days",
        plansDuration365: "365 days",
        plansInternal: "Internal",
        plansNote: "Tap \"Buy\" and scan the QR to upgrade. Quota resets at the start of each week.",

        // ========== PAYMENT / CHECKOUT ==========
        buyBtn: "Buy",
        plansDowngradeHint: "Available after your plan expires",
        checkoutTitle: "Buy plan",
        checkoutScanQr: "Scan the QR with your banking app to transfer",
        checkoutBank: "Bank",
        checkoutAccountNo: "Account number",
        checkoutAccountHolder: "Account holder",
        checkoutAmount: "Amount",
        checkoutContent: "Transfer content",
        checkoutContentWarn: "Please KEEP this content unchanged so the system can auto-confirm.",
        checkoutCopy: "Copy",
        checkoutCopied: "Copied",
        checkoutWaiting: "Waiting for your transfer…",
        checkoutWaitingHint: "After transferring, keep this screen open — your plan activates within a few minutes.",
        checkoutPaidToast: "Payment successful! Your plan is now active.",
        checkoutExpiresIn: "Expires in",
        checkoutExpired: "This order has expired.",
        checkoutRetry: "Create a new order",
        checkoutCreateError: "Couldn't create the order. Please try again.",
        checkoutNotConfigured: "Payment isn't configured yet. Please contact an admin.",

        // Payment status labels (sync with PaymentOrderStatuses .NET)
        payStatusPending: "Pending",
        payStatusPaid: "Paid",
        payStatusExpired: "Expired",
        payStatusCancelled: "Cancelled",
        payStatusRefunded: "Refunded",

        // ========== APP SHELL TITLES ==========
        homeTitle: "Home",
        conversationTitle: "Conversation",

        // ========== SCAN ==========
        scanTitle: "Scan document",
        scanStep1: "Step 1: Choose image",
        scanStep2: "Step 2: Choose document type",
        scanStep3: "Step 3: Choose language",

        scanFileInputAria: "Select image file",

        scanUploadSelect: "Choose image",
        scanUploadSelected: "✓ Selected",
        scanUploadSelectAria: "Select image",
        scanUploadSelectedAria: "Change selected image",

        scanPreviewAlt: "Image preview",

        scanTopicDesc: "Select document type so AI can better understand the content",

        topicLabels: {
            product: "Product information",
            history: "Historical document",
            place: "Place / Travel",
            general: "General document",
        },

        scanSourceLang: "Source language (OCR)",
        scanTargetLang: "Translate to",

        scanGroupBest: "Best supported",
        scanGroupOther: "Other languages",

        scanSubmit: "Scan & Chat",
        scanProcessing: "Processing...",
        scanHelp: "Choose an image of a document, receipt, menu, or anything you want to translate or ask about",

        scanErrNotImage: "Please select an image file",
        scanErrTooLarge: "File is too large (max 10MB)",
        scanErrSubmit: "Error while processing image. Please try again.",
        scanQuotaError:
          "You've used all your scans this week. Quota resets next week.",

        // ===== HISTORY =====
        historyTitle: "Chat history",
        historyLoading: "Loading history...",
        historyLoadError: "Failed to load chat history",

        historyEmptyTitle: "No conversations yet",
        historyEmptyDesc: "Start by scanning a document",

        historyUntitled: "New conversation",
        historyOpenConversation: "Open conversation",

        historyRename: "Rename",
        historyDelete: "Delete",

        historyRenameTitle: "Rename conversation",
        historyRenamePlaceholder: "Enter conversation name...",

        historyDeleteTitle: "Delete conversation",
        historyDeleteConfirm: "Are you sure you want to delete this conversation?",

        historyRenameError: "Failed to rename conversation",
        historyDeleteError: "Failed to delete conversation",

        historySearchPlaceholder: "Search by title...",
        historyFilterAllTopics: "All topics",
        historyLoadMore: "Load more",
        historyLoadingMore: "Loading...",
        historyNoResults: "No conversations found",
        historyShowingCount: (shown: number, total: number) =>
          `Showing ${shown} of ${total}`,
        historyPaginationPrev: "Prev",
        historyPaginationNext: "Next",
        historyPageOf: (page: number, totalPages: number) =>
          `Page ${page} of ${totalPages}`,
        historyPerPage: "Per page",
        historyShowingRange: (from: number, to: number, total: number) =>
          `Showing ${from}-${to} of ${total} results`,
        historyViewGrid: "Grid view",
        historyViewList: "List view",
        historyColName: "Name",
        historyColTopic: "Topic",
        historyColCreated: "Created",
        historyColActions: "Actions",

        save: "Save",
        cancelBtn: "Cancel",
        closeBtn: "Close",
        delete: "Delete",
        // ========== CONVERSATION ==========
        convDefaultTitle: "New conversation",

        // ========== ADMIN ==========
        adminTitle: "Admin",
        adminOpenLink: "Open admin panel",
        adminAiSection: "AI configuration",
        adminModelLabel: "AI model",
        adminModelDesc: "Gemini model used to analyse & answer",
        adminModelFlash: "higher quality",
        adminModelLite: "cheaper & faster",
        adminAiMockLabel: "Mock AI",
        adminAiMockDesc: "On = canned responses (no Gemini call, no quota)",
        adminOcrMockLabel: "Mock OCR",
        adminOcrMockDesc: "On = canned OCR (no OCR.Space call)",
        adminTtsLabel: "Read aloud with Google voice (TTS)",
        adminTtsDesc:
          "On = natural Google voice; Off = the browser's default voice",
        adminSaving: "Saving...",
        adminSaved: "Saved ✓",
        adminLoadError: "Failed to load settings",
        adminSaveError: "Failed to save",

        logoutConfirmTitle: "Log out?",
        logoutConfirmMessage: "Are you sure you want to log out of this account?",

        adminUsersTitle: "User management",
        adminUsersLink: "Manage users",
        adminQuotaSection: "Free quota (per week)",
        adminFreeScans: "Scans / week",
        adminFreeAsks: "Chat questions / week",
        adminSearchUser: "Search by email or name...",
        adminFilterRole: "Filter by role",
        adminFilterPlan: "Filter by plan",
        adminSortBy: "Sort by",
        adminAll: "All",
        adminSortCreated: "Sign-up date",
        adminSortLastLogin: "Last login",
        adminSortEmail: "Email",
        adminSortName: "Name",
        adminSortPlan: "Plan",
        adminSortStatus: "Status",
        adminSortRole: "Role",
        adminSortConvos: "Conversations",
        adminSortTokens: "Tokens",
        adminSortAsc: "Ascending",
        adminSortDesc: "Descending",
        adminColUser: "User",
        adminColRole: "Role",
        adminColPlan: "Plan",
        adminColVerified: "Verified",
        adminColConvos: "Convos",
        adminColTokens: "Tokens",
        adminColQuota: "Weekly quota (scan/ask)",
        adminColStatus: "Status",
        adminColActions: "Actions",
        adminPlanPaid: "Paid",
        adminActionReset: "Reset quota",
        adminActionSuspend: "Suspend",
        adminActionUnsuspend: "Unsuspend",
        adminActionDelete: "Delete",
        adminDeleteConfirm: "Permanently delete this user (and all their data)? Cannot be undone.",
        adminMetricUsers: "Users",
        adminMetricConvos: "Conversations",
        adminMetricCalls: "AI calls",
        adminMetricCost: "Est. Gemini cost",
        adminUsersEmpty: "No users",
        adminBackToConfig: "AI config",
        adminSelfDisabled: "You can't do this to yourself",

        // ========== ADMIN PAYMENTS ==========
        adminPaymentsTitle: "Payments",
        adminPaymentsDesc: "Transaction log, approve & refund",
        adminPayFilterStatus: "Filter by status",
        adminPayColOrder: "Order",
        adminPayColUser: "User",
        adminPayColPlan: "Plan",
        adminPayColAmount: "Amount",
        adminPayColStatus: "Status",
        adminPayColCreated: "Created",
        adminPayColPaid: "Paid",
        adminPayColNote: "Note",
        adminPayColActions: "Actions",
        adminPayActionApprove: "Approve",
        adminPayActionReject: "Reject",
        adminPayActionRefund: "Refund",
        adminPayEmpty: "No transactions yet",
        adminPayApproveConfirm: "Confirm money received and grant the plan to this user?",
        adminPayRejectConfirm: "Reject / cancel this order?",
        adminPayRefundTitle: "Mark as refunded",
        adminPayRefundNote: "Note (e.g. friend — refunded manually)",
        adminPayRefundHint: "Records the refund only — does NOT revoke the user's plan.",
        adminPayActionError: "Action failed",

        // ========== ADMIN PLAN STATS + REVENUE ==========
        adminPlanStatsTitle: "Subscribers per plan",
        adminRevenueTitle: "Revenue",
        adminRevenueDesc: "Daily income statistics",
        adminRevenueRange: "Time range",
        adminRevenue7d: "7 days",
        adminRevenue30d: "30 days",
        adminRevenue90d: "90 days",
        adminRevenueTotal: "Total revenue",
        adminRevenueOrders: "Paid orders",
        adminRevenueRefunded: "Refunded",
        adminRevenueChartTitle: "Revenue by day",
        adminRevenuePeak: "Peak",
        adminRevenueEmpty: "No revenue yet",
        adminRevenueNote: "Revenue = paid orders (refunds excluded). VN timezone.",

        profileTitle: "Account",
        profileLink: "Account",
        profileAccount: "Account info",
        profileEmail: "Email",
        profileName: "Name",
        profileEmailVerified: "Email verification",
        profileVerifiedYes: "Verified",
        profileVerifiedNo: "Not verified",
        profileRole: "Role",
        profilePlan: "Plan",
        profileMemberSince: "Member since",
        profileQuota: "This week's quota",
        profileQuotaScans: "Scans",
        profileQuotaAsks: "Questions",
        profileQuotaReset: "Resets at",
        profileUnlimited: "Unlimited",
        profileEdit: "Edit",
        profileEditTitle: "Edit profile",
        profileSave: "Save",
        profileCancel: "Cancel",
        profileNameSaved: "Name updated ✓",
        profileNameError: "Couldn't update name. Please try again.",
        profileChangeAvatar: "Change avatar",
        profileRemoveAvatar: "Remove",
        profileRemoveAvatarTitle: "Remove avatar?",
        profileRemoveAvatarConfirm:
          "Your current avatar will be removed. Are you sure?",
        profileAvatarSaved: "Avatar updated ✓",
        profileAvatarRemoved: "Avatar removed ✓",
        profileAvatarError: "Couldn't update avatar. Please try again.",
        profileAvatarTooLarge: "Image is too large (max 5MB).",
        profileAvatarNotImage: "Please select an image file.",
        verifyResend: "Send verification email",
        verifySent: "Sent ✓",
        verifyLoading: "Verifying...",
        verifySuccess: "Email verified!",
        verifyError: "Invalid or expired link.",
        back: "Back",
        authOr: "or",
        authGoogleSubtitle: "Continue with your Google account",
        authTermsNote:
          "By continuing, you agree to the Terms & Privacy Policy.",

        convBackToHistoryAria: "Back to history",
        convBackToHistoryTitle: "Back to conversations",

        convActionRename: "Rename",
        convActionDelete: "Delete",

        convEmptyText: "Start asking questions about your document",

        convStreamError: "Scan stream failed",
        convSendError: "Failed to send message. Please try again.",
        convSendErrorBubble: "An error occurred. Please try again.",

        convInputPlaceholder: "Type your question...",
        convInputAria: "Message input",
        convExpandAria: "Expand input",
        convComposeTitle: "Compose your question",
        convCharCount: "{count}/{max} characters",
        convCharLimitReached: "Character limit reached",

        convSendAria: "Send message",
        convStopAria: "Stop generating",
        convSpeakAria: "Read answer aloud",
        convStopSpeakAria: "Stop reading",
        convSpeakUnsupported: "Your browser doesn't support text-to-speech",

        convBtnSendText: "Send",
        convBtnStopText: "Stop",

        convImageAlt: "Uploaded image",
        convImagePreviewAlt: "Preview image",

        convRenameTitle: "Rename conversation",
        convRenamePlaceholder: "Enter conversation name...",
        convRenameError: "Unable to rename conversation",

        convDeleteTitle: "Delete conversation",
        convDeleteConfirm: "Are you sure you want to delete this entire conversation?",
        convDeleteError: "Unable to delete conversation",

        benefitFastDescription: "Lightning-fast processing with instant results",
        benefitAccurateDescription: "High-precision OCR with AI validation",
        benefitPrivateDescription: "Your data stays secure and private",
        statAccuracy: "Accuracy",
        statSpeed: "Avg. Speed",
        statConversations: "Languages",

        historyBtnDescription: "Access your previous conversations",
        scanBtnDescription: "Scan documents instantly with AI-powered OCR",

        historyConversations: "Conversations",
        scanUploadCamera: "Take photo",
        scanUploadGallery: "Upload from gallery",

        // ========== COMMON ==========
        commonRetry: "Retry",
        commonClose: "Close",

        // ========== VERIFY ==========
        verifyErrorTitle: "Verification failed",

        // ========== AUTH ==========
        authRegisterRedirect: "Redirecting to sign in...",

        // ========== HOME ==========
        homeGreetingMorning: "Good morning,",
        homeGreetingAfternoon: "Good afternoon,",
        homeGreetingEvening: "Good evening,",
        homeGreetingFallback: "there",
        homeCtaTitle: "Ready to scan?",
        homeCtaDesc: "Snap or upload a photo to extract text and ask AI instantly.",
        homeQuotaTitle: "This week's quota",
        homeQuotaPeriod: "7 days",
        homeQuotaLabel: "Scans remaining",
        homeQuotaUsedSuffix: "used",
        homeQuotaUnknown: "Your quota will appear once usage data is available.",
        homeQuotaUnlimited: "Unlimited",
        homeQuotaScans: "Scans",
        homeQuotaAsks: "Questions",
        homeQuotaResetHint: "Quota resets at the start of next week.",
        homeQuickActions: "Quick actions",
        homeTipsTitle: "Tips",
        homeTip1: "Take clear, well-lit photos so the AI reads more accurately.",
        homeTip2: "Reopen History to keep chatting about a scanned image.",
        homeTip3: "Switch language and light/dark theme in Settings.",

        // ========== CONVERSATION (extra) ==========
        convQuotaError: "You've reached your quota. Upgrade or try again later.",
        convEmptyTitle: "Start the conversation",
        convRenameSuccess: "Conversation renamed",
        convDeleteSuccess: "Conversation deleted",

        // ========== HISTORY (extra) ==========
        historyDeleteSuccess: "Conversation deleted",
        historyRenameSuccess: "Conversation renamed",
        historyNoResultsDesc: "Try a different search term or topic filter.",
        historyClearFilters: "Clear filters",
        historyViewToggleLabel: "View mode",
        historyActionsFor: "Actions for",
        historyPaginationLabel: "Pagination",
        historyPaginationFirst: "First page",
        historyPaginationLast: "Last page",
    },
};
